config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/home/guest_sign_in', to: 'home#new_guest'
  root to: "home#index"
  resources :users
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :articles do
  resources :comments, only: [:create, :destroy]
  end
  get '/article/category', to: "articles#category"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    attachment :image
    has_many :comments
    has_many :likes

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :category  
    validates :category_id, presence: true

    with_options presence: true do
    validates :title
    validates :body
    end
end

app/models/category.rb
class Category < ActiveHash::Base
    self.data = [
      {id: 1, name: 'おでかけ'}, {id: 2, name: 'お買い物'}, {id: 3, name: '子育て'},
      {id: 4, name: 'グルメ'}, {id: 5, name: 'イベント'}, {id: 6, name: 'その他'}
    ]
    include ActiveHash::Associations
    has_many :articles
  end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    belongs_to :user
end

app/models/like.rb
 class Like < ApplicationRecord
    belongs_to :article
    belongs_to :user
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :articles, dependent: :destroy
  has_many :likes
  has_many :comments  
  def liked_by?(article_id)
    likes.where(article_id: article_id).exists?
  end
   
  validates :username, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def after_sign_in_path_for(resource)
      user_path(current_user)
    end
  
    def after_sign_up_path_for(resource)
      user_path(current_user)
    end
  
    def after_sign_out_path_for(resource_or_scope)
      root_path
    end
  
    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :search_category_article, only: [:index, :category, :hashtag, :search]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
    redirect_to article_path(@article), notice: '投稿に成功しました。'
    else
      render :new
    end  
  end

  def edit
    @article = Article.find(params[:id])
    if @article.user != current_user
      redirect_to articles_path, alert: '不正なアクセスです。'
    end  
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
    redirect_to article_path(@article), notice: '更新に成功しました。'
    else
      render :edit
    end  
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end
  
  def category
    @articles = @q.result
    category_id = params[:q][:category_id_eq]
    @category = Category.find_by(id: category_id)
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image, :category_id)
  end

  def search_category_article
    @q = Article.ransack(params[:q])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        comment = Comment.create(comment_params)
        redirect_to "/articles/#{comment.article.id}"
      end

      def destroy
        Comment.find_by(id: params[:id],article_id: params[:article_id]).destroy
        redirect_back(fallback_location: root_path)
      end
    
    
      private
      def comment_params
        params.require(:comment).permit(:text).merge(user_id: current_user.id, article_id: params[:article_id])
      end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def new_guest
    user = User.find_or_create_by!(username: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
  end
    sign_in user
    redirect_to user_path(current_user), notice: 'ゲストユーザーとしてログインしました。'
  end
 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :article_params
    def create
      Like.create(user_id: current_user.id, article_id: params[:id])
      
    end
  
    def destroy
      Like.find_by(user_id: current_user.id, article_id: params[:id]).destroy
    
    end
  
    private
  
    def article_params
      @article = Article.find(params[:id])
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user), notice: '更新に成功しました。'
    else
      render :edit
    end  
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<% if current_user.liked_by?(article.id) %>
 <td>
   <%= link_to destroy_like_path(article), class: "like-link", method: :DELETE, remote: true do %>
   <i class="fa fa-heart unlike-btn"></i>
<% end %>
   <%= article.likes.count %>
 </td>
<% else %>
 <td>
   <%= link_to create_like_path(article), class: "like-link", method: :POST, remote: true do %>
   <i class="fa fa-heart like-btn"></i>
<% end %>
   <%= article.likes.count %>
 </td>
<% end %>

app/views/articles/category.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        カテゴリー： <%= @category.name %>
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @articles.each do |article| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to article_path(article) do %>
                <%= attachment_image_tag article, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
          <div class="card-content">
            <p class="title is-6"><%= link_to article.title, article_path(article) %></p>
              <div class="media">
                <div class="media-left">
                  <figure class="image is-32x32">
                    <%= link_to user_path(article.user.id) do %>
                    <%= attachment_image_tag article.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                    <% end %>
                  </figure>
                </div>
                  <strong><%= link_to article.user.username, user_path(article.user.id) %></strong></div>
                  <span id="article_<%= article.id %>">
                    <%= render 'article', article: article %>    
                  </span>
             
               <div class="content">
                <time><small><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></small></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/articles/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        記事編集
      </h1>
    </div>
  </div>
</section>

<% if @article.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @article do |f| %>
          <div class="field">
            <%= f.label :title, "記事タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
           <div class="field">
            <%= f.label :title, "カテゴリー", class: "label" %>
            <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "選択してください" }, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :body, "本文", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        記事一覧
      </h1>
    </div>
  </div>
</section>

<div class="container">
  <h2 class="title">
    <%= search_form_for @q, url: article_category_path do |f| %>
    <%= f.collection_select :category_id_eq, Category.where.not(id: 0), :id, :name, include_blank: "カテゴリー検索" %>
    <%= f.submit '検索' %>
<% end %>
  </h2>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @articles.each do |article| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to article_path(article) do %>
                <%= attachment_image_tag article, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <p class="title is-6"><%= link_to article.title, article_path(article) %></p>
           
              <div class="media">
                <div class="media-left">
                  <figure class="image is-32x32">
                    <%= link_to user_path(article.user.id) do %>
                    <%= attachment_image_tag article.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                    <% end %>
                  </figure>
                </div>
                  <strong><%= link_to article.user.username, user_path(article.user.id) %></strong></div>
                <span id="article_<%= article.id %>">
                  <%= render 'article', article: article %>    
                </span>
             
                <div class="content">
                <time><small><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></small></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規記事作成
      </h1>
    </div>
  </div>
</section>

<% if @article.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @article do |f| %>
          <div class="field">
            <%= f.label :title, "記事タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :title, "カテゴリー", class: "label" %>
            <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "選択してください" }, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :body, "文章を入力", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        記事詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @article, :image, fallback: "no-image.png" %>
            </figure>
          </div>
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"><%= @article.title %></p>     
                <strong>カテゴリー：<%= @article.category.name %></strong>
            </div>  
          </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <td><%= simple_format @article.body %></td>
                </tr>
              </table>
                <% if @article.user.id == current_user.id %>
                <%= link_to "編集", edit_article_path(@article), class: "button is-success" %>
                <% end %>
            <div>
              <span id="article_<%= @article.id %>">
                <%= render 'article', article: @article %>    
              </span>
            </div>  
            </div>
          </div>
        </div>
      </div>        

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
             <%= @article.user.username %>
          </p>
      <div class="panel-block">
          <p class="control">
             <%= @article.user.profile %>
          </p>
      </div>
             <%= link_to user_path(@article.user), class: "panel-block" do %>
          <span class="panel-icon">
          <i class="fas fa-user" aria-hidden="true"></i>
          </span>
             <%= @article.user.username %> さんのページへ
             <% end %>
        </article>
     
    <article class="media">
      <figure class="media-left">
        <% @comments.each do |comment| %>
         <p class="image is-48x48">
        <%= link_to user_path(@article.user.id) do %>
        <%= attachment_image_tag comment.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
        <% end %>
         </p>
      </figure>
   
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= link_to comment.user.username, "/users/#{comment.user_id}" %></strong><br>
            <%= comment.text %><br>
            <time><small><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></small></time>
          </p>
            <% if current_user == comment.user %>
          <p><%=link_to "コメント削除", article_comment_path(comment.article.id, comment.id), method: :delete %></p>
            <% end %>
    </article>
    <article class="media">
            <% end %>
      
<article class="media">
  <figure class="media-left">
    <p class="image is-48x48">
      <%= link_to user_path(@article.user.id) do %>
        <%= attachment_image_tag current_user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
      <% end %>
    </p>
  </figure>
  <div class="media-content">
    <div class="field">
      <p class="control">
        <% if current_user %>
      <%= form_with(model: [@article, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", cols: "47", rows: "8" %><br>
        <%= form.submit "送信", class: "button is-primary" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
      </p>
     </div>  
    </div>
   </div>
  </div>
 </div>
</article>
</section>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.1/css/bulma.min.css">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <style>
    @media(max-width: 500px) {
      .reverse-columns {
        flex-direction: column-reverse;
        display: flex;
      }
    }

    .titled {
      font-family: 'Merriweather', serif !important;
      font-size: 58px !important;
      font-weight: 400 !important;
      line-height: 64px !important;
    }

    .subtitled {
      font-family: 'Merriweather', serif !important;
      font-size: 22px !important;
      font-weight: 400 !important;
      line-height: 36px !important;
    }

    .notification.is-info {
	margin-bottom: 0;
}
  </style>
</head>

<body>
  

  <!-- Hero del producto -->
  <section class="hero is-white is-fullheight">
    <div class="hero-body">
      <div class="container">
        <div class="columns  is-vcentered reverse-columns">
          <div class="column
          is-10-mobile is-offset-1-mobile
          is-10-tablet is-offset-1-tablet
          is-5-desktop is-offset-1-desktop
          is-5-widescreen is-offset-1-widescreen
          is-5-fullhd is-offset-1-fullhd" data-aos="fade-down">
            <h1 class="title titled is-1 mb-6">
              あなたの街、ibarakiへようこそ
            </h1>
            <h2 class=" subtitled subtitle has-text-grey is-4 has-text-weight-normal is-family-sans-serif">
             美しく住みやすい街、ibarakiにお住まいの方向けの情報共有サイトです。お住まいの方しか知らない
             コアな情報をみんなでシェアしましょう!!
            </h2>
            <div class="buttons">
              <button class="button is-primary"><%= link_to "ログイン", new_user_session_path %></button>
              <button class="button is-primary"><%= link_to "新規登録", new_user_registration_path %></button>
              <button class="button is-warning"><%= link_to 'ゲストログイン（閲覧用）', home_guest_sign_in_path, method: :post %></button>
            </div>
          </div>
          <div data-aos="fade-right" class="column
          is-10-mobile is-offset-1-mobile
          is-10-tablet is-offset-1-tablet
          is-4-desktop is-offset-1-desktop
          is-4-widescreen is-offset-1-widescreen
          is-4-fullhd is-offset-1-fullhd">
            <figure class="image is-square">
            <img src="/assets/machi.png" alt="">
            </figure>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="hero is-white is-fullheight">
    <div class="hero-body">
      <div class="container">
        <div class="columns  is-vcentered">
          <div data-aos="fade-left" class="column
          is-10-mobile is-offset-1-mobile
          is-10-tablet is-offset-1-tablet
          is-4-desktop is-offset-1-desktop
          is-4-widescreen is-offset-1-widescreen
          is-4-fullhd is-offset-1-fullhd">
            <figure class="image is-square">
               <img src="/assets/familly.png" alt="">
            </figure>
          </div>
          <div data-aos="fade-down" class="column
          is-10-mobile is-offset-1-mobile
          is-10-tablet is-offset-1-tablet
          is-5-desktop is-offset-1-desktop
          is-5-widescreen is-offset-1-widescreen
          is-5-fullhd is-offset-1-fullhd">
            <h1 class="titled title is-1 mb-6">
              子育てについて悩みがある
            </h1>
            <h2 class="subtitled subtitle">
              ibarakiは子育ての悩みを解決します。地域限定の情報のみを共有できるので
              市限定の子育ての制度なども共有できます
            </h2>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="hero is-white is-fullheight">
    <div class="hero-body">
      <div class="container">
        <div class="columns  is-vcentered reverse-columns">
          <div data-aos="fade-right" class="column
          is-10-mobile is-offset-1-mobile
          is-10-tablet is-offset-1-tablet
          is-5-desktop is-offset-1-desktop
          is-5-widescreen is-offset-1-widescreen
          is-5-fullhd is-offset-1-fullhd">
            <h1 class="title titled is-1 mb-6">
              お得な情報もすぐわかる、すぐ共有できる
            </h1>
            <h2 class="subtitle subtitled">
             今日、このスーパーは特売日、この施設では無料のイベントの開催日、などibaraki
             ではお得な情報もすぐに確認ができます
            </h2>
          </div>
          <div data-aos="fade-down" class="column
          is-10-mobile is-offset-1-mobile
          is-10-tablet is-offset-1-tablet
          is-4-desktop is-offset-1-desktop
          is-4-widescreen is-offset-1-widescreen
          is-4-fullhd is-offset-1-fullhd" data-aos="fade-up">
            <figure class="image is-square">
             <img src="/assets/kaimono.png" alt="">
            </figure>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/TypewriterJS/2.13.1/core.min.js"></script>
  <script>
    new Typewriter('#typewriter', {
      strings: ['typewriter', 'Effect', 'typewriter.js', 'example'],
      autoStart: true,
      loop: true,
    });
  </script>
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({
      once: true
    });
  </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ibaraki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
     <div class="notification is-info">
      <p class="notice"><%= notice %></p>
     </div>
    <% end %>
    <% if flash[:alert] %>
     <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
     </div>
    <% end %>

     <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">ibaraki</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

    <% if user_signed_in? %>
     <div id="navbarExampleTransparentExample" class="navbar-menu">
     <div class="navbar-end">
      <div class="navbar-item">
        <%= link_to "記事一覧", articles_path, class: "navbar-item button is-warning is-light" %>
      </div>
       <div class="navbar-item">
            <%= link_to "新規投稿", new_article_path, class: "navbar-item button is-warning is-light" %>
       </div>
       
        <div class="navbar-item">  
            <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
        </div>
        <div class="navbar-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
        </div>
      </div>
    </div>
  </div>
</div> 
</div>      
    <% else %>
     <div id="navbarExampleTransparentExample" class="navbar-menu">
      </div>
      <div class="navbar-end">
        <div class="navbar-item"> 
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
        </div>
      </div> 
      <div class="navbar-end">
      <div class="navbar-item">
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %> 
      </div>
     </div>     
    <% end %>
   </nav>
  <%= yield %>
 </body>
</html>

app/views/likes/create.js.erb
document.getElementById('article_<%= @article.id %>').innerHTML = '<%= j(render @article) %>'

app/views/likes/destroy.js.erb
document.getElementById('article_<%= @article.id %>').innerHTML = '<%= j(render @article) %>'

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
  
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png" %>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
            <tr>
            <td class="is-size-4">
            <strong><%= @user.username %></strong>
            </td>
          <% if @user.id == current_user.id %>
            <td>
              <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
            </td>
              <% end %>
            </tr>
          </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.articles.each do |article| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= attachment_image_tag article, :image, fallback: "no-image.png" %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to article_path(article), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この記事を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_article_path(article), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この記事を編集する
                    <% end %>
                    <%= link_to article_path(article), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この記事を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>